on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  make_dist:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clone aether
        run: cd .. && git clone https://github.com/gfous/aether
      - name: Compile and Copy Artifacts
        run: mkdir build && cd build &&
             cmake -DCMAKE_BUILD_TYPE=Release .. &&
             cmake --build . &&
             mkdir dist && cd dist &&
             cp ../Release/arbiter.exe . &&
             cp ../Release/arbiter.exp . &&
             cp ../Release/arbiter.lib . &&
             cp ../aether/Release/aether.lib . &&
             cp ../aether/vendor/cglm/Release/cglm.exp . &&
             cp ../aether/vendor/cglm/Release/cglm.lib . &&
             cp ../aether/vendor/cglm/Release/cglm-0.dll . &&
             cp ../aether/vendor/glfw/src/Release/glfw3.lib . &&
             cp ../aether/vendor/nativefiledialog-extended/src/Release/nfd.lib . &&
             cd .. && tar.exe -a -c -f dist.zip dist
      - name: Add to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/dist.zip
